version: '3.4'

services:
  flaskdemo:
    image: flaskdemo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    networks:
      - python-network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - python-network

networks:
  python-network: