apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        editor: vscode
    spec:
      containers:
      - name: nginx-depl
        image: nginx:alpine
        ports:
          - containerPort: 8080