kind: Service
apiVersion: v1
metadata:
  name:  nginx-service
spec:
  selector:
    app:  nginx
  type:  ClusterIP
  ports:
  - name:  http-custom-port
    protocol: TCP
    port:  80
    targetPort:  8080
