apiVersion: v1
kind: Secret
metadata:
  name:  mongodb-secret
type: Opaque
data:
  #  secretKey:  BASE64_ENCODED_VALUE
   mongo-root-username: bW9uZ28=
   mongo-root-password: bW9uZ28=
---
# service
apiVersion: v1
kind: Service
metadata:
  name:  mongodb-service
spec: 
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
