---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: flaskapp
  region: ${AWS_REGION}
  version: "1.22"

# availabilityZones: ["${AZS[0]}", "${AZS[1]}", "${AZS[2]}"]

managedNodeGroups:
- name: primary
  spot: true
  minSize: 3
  maxSize: 6
  instanceType: t2.small
  ssh:
    allow: true
    publicKeyName: Kubernetes_Cluster