---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: flaskapp
  region: us-east-1
  version: "1.22"

# availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

vpc:
  subnets:
    public:
      us-east-1a: { id: subnet-0c9f1e6a5013fb40b }
      us-east-1b: { id: subnet-03174f36718026f94 }
      us-east-1c: { id: subnet-06df83ae55f6314b1 }
      us-east-1d: { id: subnet-05ea5978e24ab5be4 }
      us-east-1e: { id: subnet-011d325c66a1dc066 }
      us-east-1f: { id: subnet-00bf0529cf006941c }

managedNodeGroups:
- name: primary
  spot: true
  instanceType: t2.small
  ssh:
    allow: true
    publicKeyName: Kubernetes_Cluster
  tags:
      nodegroup-role: my-worker

nodeGroups:
  - name: primary
    labels: { role: master }
    instanceType: t2.small
    desiredCapacity: 3
    ssh:
      allow: true
      publicKeyName: Kubernetes_Cluster
    tags:
      nodegroup-role: my-worker
  - name: worker
    labels: { role: worker }
    instanceType: t2.small
    desiredCapacity: 3
    ssh:
      allow: true
      publicKeyName: Kubernetes_Cluster
    tags:
      nodegroup-role: my-worker

