---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: flaskapp
  region: us-east-1
  version: "1.22"

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t3.small
  ssh:
     publicKeyName: Kubernetes_Cluster
