---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: flaskapp
  region: ${AWS_REGION}
  version: "1.22"

availabilityZones: ["${AZS[0]}", "${AZS[1]}", "${AZS[2]}"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t3.small
  ssh:
     publicKeyName: Kubernetes_Cluster