---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: flaskapp-v3
  region: us-east-1
  version: "1.22"

# availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

# vpc:
#   subnets:
#     public:
#       us-east-1a: { id: subnet-0c9f1e6a5013fb40b }
#       us-east-1b: { id: subnet-03174f36718026f94 }
#       us-east-1c: { id: subnet-06df83ae55f6314b1 }


nodeGroups:
- name: primary-worker
  instanceType: t3.medium
  desiredCapacity: 1
  ssh:
    allow: true
    publicKeyName: Kubernetes_Cluster
    # sourceSecurityGroupIds: ["sg-0829d33e9e3313dd2"]

